# Generated by Django 2.2.1 on 2019-05-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2048)),
                ('isbn', models.CharField(max_length=1024)),
                ('number', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('room_number', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=6)),
                ('section', models.CharField(max_length=6)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
