# Generated by Django 2.2.1 on 2019-05-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.CharField(default='none', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='isbn',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='teachercard',
            name='grade',
            field=models.CharField(choices=[('K4', 'K4'), ('K5', 'K5'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=6),
        ),
        migrations.AlterField(
            model_name='teachercard',
            name='section',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
