# Generated by Django 2.2.1 on 2019-06-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190523_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='note',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
